server:
  port: 8081
  servlet:
    context-path: /admins
spring:
  application:
    name: ADMIN-SERVICE
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/db_admins_test
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:arrahmankm}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:emailaddress@gmail.com}
    password: ${MAIL_PASSWORD:password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
jwt:
  secret:
    key:
      admins:
        access_token: IaiYw5wsEs9UNE6Y557it0VyIVaMz9PZmXx8EsqlZFM
        expiration: 6000000
        refresh_token:
          expiration: 86400000
      common: IaiYw5wsEs9UNE6Y557it0VyIVaMz9PZmXx8EsqlZFM
  filter:
    disable:
      request:
        uris: /admins/api/v1/auth/**,
              /admins/api/v1/public/**
